---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    k8s.kuboard.cn/name: {{ .Release.Name }}
data:
  mysqld.cnf: |
    [mysqld]
    datadir = /var/lib/mysql
    bind-address = 0.0.0.0
    # disable symbolic-links
    symbolic-links=0
    max_allowed_packet=64M
    max_connections=2000
    default_storage_engine=INNODB
    # ignore table name case
    lower_case_table_names=1
    skip_name_resolve
    character_set_server=utf8mb4
    # disable timestamp to null
    explicit_defaults_for_timestamp=ON
    # enable binlog
    server-id = {{ .Values.mysql.serverId }}
    log-bin = mysql-bin
    binlog_format = ROW
    binlog_row_image = FULL
    expire_logs_days = 7
