apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    k8s.kuboard.cn/name: {{ .Release.Name }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.rootPassword | b64enc | quote }}
